### ISSUE TITLE
Does not work with angular 18

### ISSUE THREAD

**Issue by foxyyyyyyyyyyyyy** [mattlewis92/angularx-flatpickr#56]
### Describe the bug

FlatpickrModule.forRoot() is not supported in angular18 

### Minimal reproduction of the problem with instructions

just set it up in an angular 18 application

### @angular/core version

18.1.1

### angularx-flatpickr version

8.0.0

### Browser name and version

chrome latest

**Comment by aparzi** [comment]
Hi @foxyyyyyyyyyyyyy,
do you have a standalone based project?

**Comment by foxyyyyyyyyyyyyy** [comment]
Yes I'm using angular 19 with ssr and standalone

**Comment by foxyyyyyyyyyyyyy** [comment]
Updated from angular 18 to angular 19 in the last days but shouldn't change anything on compatability

**Comment by aparzi** [comment]
Ok thanks.
The problem is that you are working with a standalone project (rightly so) the library needs to be adapted. We will try to do it as soon as possible.

@mattlewis92 does it make sense to you or do you think you should we proceed differently? Also the #57 issue is also connected to this type of problem
